### ISSUE TITLE
想问下  你的这个项目是怎么打包成exe的，看上去不像是用了electron

### ISSUE THREAD

**Issue by LuckyCenter** [qianjiachun/bilibili-danmaku-tracker#1]
想问下  你的这个项目是怎么打包成exe的，看上去不像是用了electron

**Comment by qianjiachun** [comment]
并没有打包成exe。只是另外做了一个exe用于“编译”src下的代码。语言是易语言，主要做了一些文件内容拼接。源码在同目录下开源了，就是那个.e文件

**Comment by LuckyCenter** [comment]
挺有趣的项目  就是希望大佬能把README再完善一下，不然没接触过这种类型的可能玩不来

**Comment by qianjiachun** [comment]
哈哈，这个readme其实是同步在greasyfork上的，这个项目也就是个油猴脚本。我再完善一下吧，谢谢关注

**Comment by qianjiachun** [comment]
已稍微完善了readme
