### ISSUE TITLE
老哥，有点小问题

### ISSUE THREAD

**Issue by like044041** [qianjiachun/bilibili-danmaku-tracker#4]
https://www.bilibili.com/bangumi/play
这个播放地址下的弹幕查了都没反应，正常地址的视频里就能查。

**Comment by qianjiachun** [comment]
我这测试了一下好像没问题呀？我随便点了一个番进去，都可以

**Comment by like044041** [comment]
啊? 原来是我自己的问题吗,这要怎么看哪里出问题了?

**Comment by qianjiachun** [comment]
方便的话，QQ远程看一下？189964430

**Comment by like044041** [comment]
不用了老哥,确实是我自己的问题,我找到了.

**Comment by qianjiachun** [comment]
好的
