### ISSUE TITLE
脚本出问题了

### ISSUE THREAD

**Issue by Harry2336** [qianjiachun/bilibili-danmaku-tracker#5]
大佬，好像用不了啊，任何弹幕点击都没办法查看啦

**Comment by qianjiachun** [comment]
亲测可用
另外暂时不维护任何项目







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月19日(星期一) 晚上10:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [qianjiachun/bilibili-danmaku-tracker] 脚本出问题了 (Issue #5)





 
大佬，好像用不了啊，任何弹幕点击都没办法查看啦

**Comment by Harry2336** [comment]
我怎么试都没用，换了浏览器，开了无痕，卸载油猴重装都不行，之前都好好的，也不知道是咋回事/(ㄒoㄒ)/~~

**Comment by qianjiachun** [comment]
发个视频链接给我




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月20日(星期二) 下午5:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qianjiachun/bilibili-danmaku-tracker] 脚本出问题了 (Issue #5)





 
我怎么试都没用，换了浏览器，开了无痕，卸载油猴重装都不行，之前都好好的，也不知道是咋回事/(ㄒoㄒ)/~~

**Comment by Harry2336** [comment]
https://www.bilibili.com/video/BV1q14y1P78z/?vd_source=6b0b7b2888d83fce0e86f8927c6d7f9a

**Comment by qianjiachun** [comment]
2022年12月26日11:24:22 亲测没问题






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/bilibili-danmaku-tracker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月26日(星期一) 中午11:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qianjiachun/bilibili-danmaku-tracker] 脚本出问题了 (Issue #5)





 
https://www.bilibili.com/video/BV1q14y1P78z/?vd_source=6b0b7b2888d83fce0e86f8927c6d7f9a

**Comment by Harry2336** [comment]
好的，那可能是我这边出问题了，过两天换个新电脑试试

**Comment by Harry2336** [comment]
大佬，我发现问题所在了。我今天偶然看番剧的时候发现，使用脚本替换网页端b站播放器到旧版本，这个查询弹幕脚本就能正常使用；但是回到最新也就是默认的播放器就失效了。我不会替换普通视频页面的播放器，只是用番剧页相关脚本的时候发现这个问题的。目前的最新播放器版本号：3.26.1-7452583b

**Comment by Harry2336** [comment]
好的好的，麻烦大佬了

**Comment by Pigjrzzy** [comment]
> 好的好的，麻烦大佬了

想问下现在用得了吗？如果可以的话该怎么操作？谢谢了！

**Comment by Pigjrzzy** [comment]
> 2022年12月26日11:24:22 亲测没问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "qianjiachun/bilibili-danmaku-tracker" ***@***.***&gt;; 发送时间:&nbsp;2022年12月26日(星期一) 中午11:23 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [qianjiachun/bilibili-danmaku-tracker] 脚本出问题了 (Issue #5) https://www.bilibili.com/video/BV1q14y1P78z/?vd_source=6b0b7b2888d83fce0e86f8927c6d7f9a — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

大佬大佬现在可以用吗？刚试了试查不了诶QAQ

**Comment by qianjiachun** [comment]
> > 2022年12月26日11:24:22 亲测没问题
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "qianjiachun/bilibili-danmaku-tracker" _**@**_._**>; 发送时间: 2022年12月26日(星期一) 中午11:23 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [qianjiachun/bilibili-danmaku-tracker] 脚本出问题了 (Issue #5) https://www.bilibili.com/video/BV1q14y1P78z/?vd_source=6b0b7b2888d83fce0e86f8927c6d7f9a — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 大佬大佬现在可以用吗？刚试了试查不了诶QAQ

你好，现在可以使用。
![image](https://user-images.githubusercontent.com/43806319/226652792-8fcd5575-e2f2-4a75-8a81-07bdf2452f49.png)
