### ISSUE TITLE
2023-06-25更新的插件无法使用

### ISSUE THREAD

**Issue by bswaterb** [qianjiachun/bilibili-danmaku-tracker#6]
![image](https://github.com/qianjiachun/bilibili-danmaku-tracker/assets/50270641/44d1465f-410a-4e98-a961-25ab52c1572e)

**Comment by qianjiachun** [comment]
方便发一下该视频的网址吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月25日(周日) 晚上6:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/bilibili-danmaku-tracker] 2023-06-25更新的插件无法使用 (Issue #6)

**Comment by bswaterb** [comment]
图中的是这个视频：https://www.bilibili.com/video/BV1Qz4y1t7HH  
在我这里打开过的视频都没法用插件的功能，油猴的评论区今天也有朋友反应相同的问题

**Comment by bswaterb** [comment]
> 方便发一下该视频的网址吗？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年6月25日(周日) 晚上6:11 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [qianjiachun/bilibili-danmaku-tracker] 2023-06-25更新的插件无法使用 (Issue #6) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

图中的是这个视频：https://www.bilibili.com/video/BV1Qz4y1t7HH
在我这里打开过的视频都没法用插件的功能，油猴的评论区今天也有朋友反应相同的问题

**Comment by qianjiachun** [comment]
2023.06.25.02 已修复
