### ISSUE TITLE
2024-12-11更新之后，无法显示查询结果

### ISSUE THREAD

**Issue by Yamakaze-sukida** [qianjiachun/bilibili-danmaku-tracker#8]
2024-12-11更新之后，无法显示查询结果，只显示“请先左键选中弹幕再右键查询”

**Comment by qianjiachun** [comment]
我这测试是正常的
方便加个QQ189964430 详细看一下吗

**Comment by Yamakaze-sukida** [comment]
> 我这测试是正常的 方便加个QQ189964430 详细看一下吗

加你了，尾号4416

**Comment by qianjiachun** [comment]
已于2024.12.12.01版本修复
